---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy calico namespace to first master
  template:
    src: "calico.namespace.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/calico-namespace.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy calico manifest to first master
  template:
    src: "calico.crds.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/calico-crds.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
